version: "3"
services:
  mariadb:
    image: mariadb:10.5.4
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: tree
      TZ: "Asia/Tokyo"
volumes:
  mariadb-data:
    driver: local
